name: Create an S3 Bucket

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  creating_bucket:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-central-1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        env:
          TF_VAR_bucket_name: ${{ secrets.BUCKET_NAME }}
        run: terraform apply -auto-approve

      - name: Upload files to S3 bucket
        run: |
          aws s3 cp index.html s3://${{ secrets.BUCKET_NAME }}/index.html
          aws s3 cp --recursive imagen/ s3://${{ secrets.BUCKET_NAME }}/images/
          aws s3 cp --recursive styles/ s3://${{ secrets.BUCKET_NAME }}/styles/